### ISSUE TITLE
Some caching issues related to labels

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#124]
If I make the following addition (adding a `!` to the end of the literal) and replace the data in the RDF store.

```diff
<https://linked.data.gov.au/def/address-type> a owl:Ontology,
        skos:ConceptScheme ;
    dcterms:created "2020-03-25"^^xsd:date ;
    dcterms:creator <https://linked.data.gov.au/org/gsq> ;
    dcterms:modified "2023-03-16"^^xsd:date ;
    dcterms:provenance "Derived from  Australian Standard AS 4590.1:2017" ;
    dcterms:publisher <https://linked.data.gov.au/org/gsq> ;
-    skos:definition "The role or use of the address in relation to a party. An address may have more than one purpose."@en ;
+    skos:definition "The role or use of the address in relation to a party. An address may have more than one purpose.!"@en ;
    skos:hasTopConcept <https://linked.data.gov.au/def/address-type/business-address>,
        <https://linked.data.gov.au/def/address-type/delivery-address>,
        <https://linked.data.gov.au/def/address-type/overseas-address>,
        <https://linked.data.gov.au/def/address-type/postal-address>,
        <https://linked.data.gov.au/def/address-type/primary-property-address>,
        <https://linked.data.gov.au/def/address-type/residential-address>,
        <https://linked.data.gov.au/def/address-type/secondary-property-address> ;
-     skos:prefLabel "Address Type"@en .
+     skos:prefLabel "Address Type!"@en .
```

Prez is combining the results from the RDF store with a local cache and the result becomes:

```turtle
<https://linked.data.gov.au/def/address-type> a owl:Ontology,
        skos:ConceptScheme ;
    dcterms:created "2020-03-25"^^xsd:date ;
    dcterms:creator <https://linked.data.gov.au/org/gsq> ;
    dcterms:modified "2023-03-16"^^xsd:date ;
    dcterms:provenance "Derived from  Australian Standard AS 4590.1:2017" ;
    dcterms:publisher <https://linked.data.gov.au/org/gsq> ;
    skos:definition "The role or use of the address in relation to a party. An address may have more than one purpose.!"@en ;
    skos:hasTopConcept <https://linked.data.gov.au/def/address-type/business-address>,
        <https://linked.data.gov.au/def/address-type/delivery-address>,
        <https://linked.data.gov.au/def/address-type/overseas-address>,
        <https://linked.data.gov.au/def/address-type/postal-address>,
        <https://linked.data.gov.au/def/address-type/primary-property-address>,
        <https://linked.data.gov.au/def/address-type/residential-address>,
        <https://linked.data.gov.au/def/address-type/secondary-property-address> ;
    skos:prefLabel "Address Type"@en,
        "Address Type!"@en .
```

I suspect the caching is only for labels because notice there's still only one `skis:definition` value but two `skos:prefLabel` values.

**Comment by edmondchuc** [comment]
This is problematic when it comes to performing data loading/updates. There will be mismatch of data since Prez will keep a stale copy of the labels, presumably in the `tbox_cache.ttl`.

Performing a `curl https://api.gsq-prez.dev.kurrawong.ai/purge-tbox-cache` results in an internal server error.
JSON response: `{"detail":"Internal Server Error"}`.
Logs:
```
INFO:     58.96.44.217:0 - "GET /purge-tbox-cache HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 87, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/prez/app.py", line 78, in add_cors_headers
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/prez/routers/management.py", line 15, in purge_tbox_cache
    os.unlink("../tbox_cache.ttl")
FileNotFoundError: [Errno 2] No such file or directory: '../tbox_cache.ttl'
```

Overall, I'd like to get an understanding of why we need a tbox cache, and if it's not required, remove it to simplify the process of performing updates to the RDF store.

**Comment by hjohns** [comment]
Anything from Prez UI will require the annotated labels every time (through a secondary query).
Performance problems to get labels every time.

Options: (1 recommended, 2 optional, 3 for consideration, 4 longer term)
1. Fix purge option to be able to update the cache. Delete on disk cache, update in memory. Restart Prez required.
2. Validate if adding to the query to get labels every time reduces the performance significantly. Optionals cause issues, could be refactored to a union, but adds complexity.
3. Consider including common ontologies in Prez.
4. Use a separate cache like Redis. For horizontal scaling considerations.

**Comment by recalcitrantsupplant** [comment]
Will be resolved by https://github.com/RDFLib/prez/issues/124

- on disk cache has been removed
- NB addition of /tbox-cache endpoint which shows the tbox cache; also fix of /purge-tbox-cache endpoint.
- no restart of prez required

**Comment by edmondchuc** [comment]
Closed in https://github.com/RDFLib/prez/pull/127.
